name: Performance Guardrail

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  perf-check:
    name: Bundle size & build budget
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run performance budget check
        run: npm run perf:check
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1
          MP_KEEP_BUILD_OUTPUT: 1

      - name: Upload metrics snapshot
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: perf-metrics
          path: .next/perf-metrics.json
          if-no-files-found: ignore
