name: Wizard QA Suite

on:
  pull_request:
    paths:
      - "app/wizard/**"
      - "lib/wizard/**"
      - "tests/wizard/**"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/wizard-tests.yml"
  push:
    branches:
      - main
    paths:
      - "app/wizard/**"
      - "lib/wizard/**"
      - "tests/wizard/**"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/wizard-tests.yml"

jobs:
  wizard-tests:
    name: Run Wizard QA
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run wizard unit tests
        run: npm run test:wizard
        env:
          NEXT_TELEMETRY_DISABLED: 1
